### ISSUE TITLE
A missing semicolon threw formatting request exception

### ISSUE THREAD

**Issue by victorshx** [dart-lang/dart_style#1060]
Dart SDK version: 2.13.3 (stable) (Wed Jun 9 12:44:44 2021 +0200) on "windows_x64"

The following Flutter code can compile, and the analyzer did not highlight any syntax error. 

```dart
Future<String?> _updateRemark(String? previousRemark) async {
  String? resp = await showDialog<String>(
      context: navigatorKey.currentContext!,
      barrierColor: ColorConstant.barrierColor,
      builder: (BuildContext context) {
        String remark = previousRemark ?? '';
        return StatefulBuilder(
          builder: (context, setState) => Center(
            child: CenterDialog(
              title: 'Update remark',
              width: 400,
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  FTextField(
                    hint: 'Enter remark here...',
                    type: INPUT_TYPE.TEXTAREA,
                    value: remark,
                    onChange: (v) {
                      setState(() {
                        remark = v ?? '';
                      })
                    },
                  ),
                  SizedBox(height: SizeConstant.sm),
                  Container(
                    width: double.infinity,
                    child: FButton(
                      onPressed: () {
                        Navigator.pop(context, remark);
                      },
                      child: Typo.body('Save'),
                    ),
                  ),
                ],
              ),
            ),
          ),
        );
      });
  return resp;
}
```

However, not inserting the ending semicolon for setState will throw formatting exception.
```dart
setState(() {
   remark = v ?? '';
})
```

Error: `[Error - 5:38:16 PM] Request textDocument/formatting failed.
  Message: An error occurred while handling textDocument/formatting request
  Code: -32001 
[Error - 5:38:16 PM] An error occurred while handling textDocument/formatting request: The formatter produced unexpected output. Input was:`

Stacktrace: 
```
#0      DartFormatter.formatSource (package:dart_style/src/dart_formatter.dart:176:7)
#1      generateEditsForFormatting (package:analysis_server/src/lsp/source_edits.dart:95:33)
#2      FormattingHandler.formatFile (package:analysis_server/src/lsp/handlers/handler_formatting.dart:36:12)
#3      FormattingHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_formatting.dart:53:14)
#4      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#5      FormattingHandler.handle (package:analysis_server/src/lsp/handlers/handler_formatting.dart:47:17)
#6      MessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:150:12)
#7      ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:189:36)
#8      LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:330:47)
#9      LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:325:21)
#10     _rootRun (dart:async/zone.dart:1428:13)
#11     _CustomZone.run (dart:async/zone.dart:1328:19)
#12     _runZoned (dart:async/zone.dart:1863:10)
#13     runZonedGuarded (dart:async/zone.dart:1851:12)
#14     LspAnalysisServer.handleMessage (package:analysis_server/src/lsp/lsp_analysis_server.dart:325:5)
#15     LspByteStreamServerChannel._readMessage (package:analysis_server/src/lsp/channel/lsp_byte_stream_channel.dart:85:16)
#16     LspByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/lsp/channel/lsp_byte_stream_channel.dart:54:24)
#17     _rootRunUnary (dart:async/zone.dart:1436:47)
#18     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#21     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#22     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#23     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#24     _rootRun (dart:async/zone.dart:1420:47)
#25     _CustomZone.run (dart:async/zone.dart:1328:19)
#26     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#28     _rootRun (dart:async/zone.dart:1428:13)
#29     _CustomZone.run (dart:async/zone.dart:1328:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

**Comment by munificent** [comment]
It appears this is a bug in the Dart parser that dart_style uses: https://github.com/dart-lang/sdk/issues/47298

The parser is accepting invalid syntax, so the formatter dutifully tries to format it. Then it gets confused when the resulting output doesn't match the input (because it synthesized the missing semicolon).

Closing this issue because the fix will ultimately be in the analyzer package. Thank you for reporting this!
