### ISSUE TITLE
Parse error with constructor-tearoffs in recent analyzer

### ISSUE THREAD

**Issue by simolus3** [dart-lang/dart_style#1095]
I'm using the latest `dart_style` (package config says `2.2.1`) and the latest `analyzer` (3.3.1). In this combination, I can't format sources with constructor tearoffs:

```dart
import 'package:dart_style/dart_style.dart';

void main() {
  print(DartFormatter().format('dynamic get x => Map.new;'));
}
```

This fails with:

```
Unhandled exception:
Could not format because the source could not be parsed:

line 1, column 22 of .: This requires the 'constructor-tearoffs' language feature to be enabled.
  ╷
1 │ dynamic get x => Map.new;
  │                      ^^^
  ╵
#0      DartFormatter.formatSource (package:dart_style/src/dart_formatter.dart:144:7)
#1      DartFormatter.format (package:dart_style/src/dart_formatter.dart:72:12)
#2      main (file:///tmp/format.dart:4:25)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

I see that `dart_style` explicitly enables the `constructor-tearoffs` feature when constructing the enable flags. However, it seems like the analyzer started also checking the minimum language version? It works when I use `sdkLanguageVersion: Version(2, 15, 0),`.

**Comment by simolus3** [comment]
Oh, looks like this is already fixed in this repo. Maybe the fix should be published too?
