### ISSUE TITLE
setup-dart Missing implementation of visitExtensionTypeDeclaration crash

### ISSUE THREAD

**Issue by sortie** [dart-lang/dart_style#1260]
I tried running the formatter on the https://github.com/dart-lang/setup-dart repository but it crashed on the node files using the external keyword and JS interop:

```Hit a bug in the formatter when formatting lib/node/actions/core.dart.
Please report at github.com/dart-lang/dart_style/issues.
Exception: Missing implementation of visitExtensionTypeDeclaration
#0      ThrowingAstVisitor._throw (package:analyzer/dart/ast/visitor.dart:2911:5)
#1      ThrowingAstVisitor.visitExtensionTypeDeclaration (package:analyzer/dart/ast/visitor.dart:2526:7)
#2      ExtensionTypeDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:6846:20)
#3      SourceVisitor.visit (package:dart_style/src/source_visitor.dart:3097:10)
#4      SourceVisitor.visitCompilationUnit (package:dart_style/src/source_visitor.dart:669:7)
#5      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:3642:50)
#6      SourceVisitor.visit (package:dart_style/src/source_visitor.dart:3097:10)
#7      SourceVisitor.run (package:dart_style/src/source_visitor.dart:120:5)
#8      DartFormatter.formatSource (package:dart_style/src/dart_formatter.dart:170:26)
#9      processFile (package:dart_style/src/io.dart:145:28)
#10     processDirectory (package:dart_style/src/io.dart:126:10)
#11     formatPaths (package:dart_style/src/io.dart:64:12)
#12     FormatCommand.run (package:dart_style/src/cli/format_command.dart:153:7)
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:27)
#14     DartdevRunner.runCommand (package:dartdev/dartdev.dart:240:30)
#15     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:122:25)
#16     new Future.sync (dart:async/future.dart:305:31)
#17     CommandRunner.run (package:args/command_runner.dart:122:14)
#18     runDartdev (package:dartdev/dartdev.dart:59:29)
#19     main (file:///b/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
#20     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:293:33)
#21     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

Dart SDK version: 3.2.0-134.0.dev (dev) (Mon Sep 4 13:06:39 2023 -0700) on "linux_x64"

**Comment by munificent** [comment]
Yeah, I haven't added support for the new extension types feature yet.

**Comment by munificent** [comment]
Pretty sure this is done now since we already shipped extension types. :)
