### ISSUE TITLE
Crash on file 'library'

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart_style#358]
Create a file contain exactly the word 'library' with no whitespace:

```
RangeError: End 8 must not be greater than the number of characters in the file, 7.
#0      FileSpan.FileSpan._ (package:source_span/src/file.dart:212)
#1      SourceFile.span (package:source_span/src/file.dart:76)
#2      FormatterException.message (package:dart_style/src/formatter_exception.dart:28)
#3      processFile (package:dart_style/src/io.dart:62)
#4      formatPaths (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/third_party/pkg_tested/dart_style/bin/format.dart:174)
#5      main (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/third_party/pkg_tested/dart_style/bin/format.dart:112)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:253)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:142)
```

**Comment by lukechurch** [comment]
PS this is esp. annoying as calling toString on the Exception object also throws. So the standard error handling code doesn't work.

If you do a 
```    } on FormatterException catch (ex) {
      print (ex);
   }
```

Then you get:

```
Unhandled exception:
RangeError: End 8 must not be greater than the number of characters in the file, 7.
#0      FileSpan.FileSpan._ (package:source_span/src/file.dart:215:7)
#1      SourceFile.span (package:source_span/src/file.dart:77:16)
#2      FormatterException.message (package:dart_style/src/formatter_exception.dart:28:23)
#3      FormatterException.toString (package:dart_style/src/formatter_exception.dart:36:24)
#4      _StringBase._interpolateSingle (dart:core-patch/string_patch.dart:804)
#5      print (dart:core/print.dart:9)
#6      main (file:///Users/lukechurch/WebstormProjects/testStyle/bin/main.dart:25:7)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:253)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:142)
```

And the thing driving formatter crashes.

Devious or what?
