### ISSUE TITLE
dartfmt errors when a function argument has both annotation and a trailing comma.

### ISSUE THREAD

**Issue by yyoon** [dart-lang/dart_style#520]
We're using the recent version of `dartfmt` included in flutter/flutter@9a0a0d990308f15c3624f512aba7623739717862.

When formatting the following file (`foo.dart`)
```dart
import 'package:meta/meta.dart';

class Foo {
  final int bar;
  Foo({
    @required this.bar,
  });
}
```

by running `dartfmt -n foo.dart`, it generates the following error:
```
Hit a bug in the formatter when formatting foo.dart.
Please report at: github.com/dart-lang/dart_style/issues
Bad state: No element
#0      List.last (dart:core-patch/growable_array.dart:218)
#1      SourceVisitor.visitParameterMetadata (package:dart_style/src/source_visitor.dart:1693)
#2      SourceVisitor.visitFieldFormalParameter (package:dart_style/src/source_visitor.dart:839)
#3      FieldFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:4420)
#4      SourceVisitor.visit (package:dart_style/src/source_visitor.dart:1669)
#5      SourceVisitor.visitDefaultFormalParameter (package:dart_style/src/source_visitor.dart:690)
#6      DefaultFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:3390)
#7      SourceVisitor.visit (package:dart_style/src/source_visitor.dart:1669)
#8      SourceVisitor._visitTrailingCommaParameterList (package:dart_style/src/source_visitor.dart:2065)
#9      SourceVisitor.visitFormalParameterList (package:dart_style/src/source_visitor.dart:886)
#10     FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4725)
#11     SourceVisitor.visit (package:dart_style/src/source_visitor.dart:1669)
#12     SourceVisitor._visitBody (package:dart_style/src/source_visitor.dart:1865)
#13     SourceVisitor.visitConstructorDeclaration (package:dart_style/src/source_visitor.dart:612)
#14     ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2892)
#15     SourceVisitor.visit (package:dart_style/src/source_visitor.dart:1669)
#16     SourceVisitor.visitClassDeclaration (package:dart_style/src/source_visitor.dart:438)
#17     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1847)
#18     SourceVisitor.visit (package:dart_style/src/source_visitor.dart:1669)
#19     SourceVisitor.visitCompilationUnit (package:dart_style/src/source_visitor.dart:523)
#20     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2439)
#21     SourceVisitor.visit (package:dart_style/src/source_visitor.dart:1669)
#22     SourceVisitor.run (package:dart_style/src/source_visitor.dart:100)
#23     DartFormatter.formatSource (package:dart_style/src/dart_formatter.dart:130)
#24     processFile (package:dart_style/src/io.dart:75)
#25     formatPaths (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/third_party/pkg_tested/dart_style/bin/format.dart:222)
#26     main (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/third_party/pkg_tested/dart_style/bin/format.dart:152)
#27     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

```

I think this happens only when a function argument has an annotation and a trailing comma, but I maybe wrong.

cc @dvdwasibi, @sethladd

**Comment by sethladd** [comment]
Thanks for the report!

**Comment by sethladd** [comment]
Coolness, thanks!

**Comment by dvdwasibi** [comment]
Woot Woot!

**Comment by yyoon** [comment]
Thanks a lot!

**Comment by matanlurey** [comment]
@munificent Was the SDK updated as well? I have to use `pub global run dart_style:format` 👎

**Comment by munificent** [comment]
It's rolled into the SDK's master branch, yes. A new release of the SDK isn't out yet, but when that comes out it will have this fix.

I usually close issues here when they are fixed in this repo since from that perspective, there's no more work to be done here to roll the fix out.
